config/routes.rb
Rails.application.routes.draw do
  resources :pictures, only: [:index, :new, :show, :create]
  resources :users, only: [:show]
  resources :tags, only: [:index, :show, :new, :create]
  resources :comments, only: [:index, :show, :new, :create]
  
  
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/pictures' => 'pictures#show'

  get '/tag' => 'tags#show'
  
  get '/login' => 'sessions#new' 
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

    belongs_to :user
    belongs_to :picture


end

app/models/picture.rb
class Picture < ApplicationRecord

    belongs_to :user
    has_many :comments
    has_many :users, through: :comments
    has_many :picture_tags
    has_many :tags, through: :picture_tags

    accepts_nested_attributes_for :tags

    def tags_attributes=(tag_attributes)
        tag_attributes.values.each do |tag_attribute|
          tag = Tag.find_or_create_by(tag_attribute)
          self.tags << tag
        end
      end

    
    def self.get_all_pics_by_tag_id(tag_id) 
        PictureTag.where("tag_id = #{tag_id}")
    end

    def self.get_all_pictures_sorted_by_most_recent
        
    end

    def self.pictures_total
       Picture.all.count 
    end
end
    
    
    
    
    
    
    
    # def user_name=(username)      #<-- PELHAM
    #     self.user = User.find_or_create_by(name: username)  
    # end 

    # def user_name
    #     user.try(:username)  
    # end 
# end

app/models/picture_tag.rb
class PictureTag < ApplicationRecord
    
    belongs_to :picture 
    belongs_to :tag
    
    
    
   
end 

app/models/tag.rb
class Tag < ApplicationRecord

    has_many :picture_tags
    has_many :pictures, through: :picture_tags



end

app/models/user.rb
class User < ApplicationRecord

    has_many :pictures
    has_many :comments
    has_many :pictures, through: :comments
    has_secure_password

    validates :username, presence: true, uniqueness: true
    validates :email, uniqueness: true

    # def user_pictures               
    #     Picture.where("user_id = #{self.id}")
    # end

    # def all_pictures
    #     Picture.all
    # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    
    helper_method :current_user, :logged_in?

    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end

     def logged_in?
       current_user != nil
     end
  end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def index
        @comments = Comments.all
    end

    def show
        @comment = Comment.find(params[:id])
    end 
    
    def new
        @comment = Comment.new
    end 

    def create
        @comment = Comment.new(comment_params)
        if @comment.save
            redirect_to comment_path(@comment)
        else
            render :new
    end



    private

    def comment_params
        params.permit(:content)
    end 

end 

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

    def index
        @pictures = Picture.all
    end 

    def show
        @picture = Picture.find(params[:id])
    end

    def new
        @picture = Picture.new
    end 

    def create
    
        @picture = Picture.new(picture_params)
        @tag = Tag.new(name: picture_params[:tags_attributes]["0"][:name])
        @picture.tags << @tag
        current_user.pictures << @picture
        if @picture.save
           redirect_to picture_path(@picture)    
        else 
            render :new
        end 
    end 

    private

    def picture_params
        params.require(:picture).permit(:image_url, :title, :user_id, :tag_ids =>[], tags_attributes: [:name])   
    end
end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end 

    def create
        
        @user = User.find_by(email: params[:email])
        if @user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            flash[:success] = "Woot Woot! You Did It!"
            redirect_to user_path(@user)
        else 
            flash[:warning] = "OOPS! Try Again"
            redirect_to '/login'
        end 
    end 

    def destroy
        session.delete :user_id
        flash[:success] = "You Logged Out"
        redirect_to '/login'
    end 
end 

app/controllers/tags_controller.rb
class TagsController < ApplicationController

    def index
        @tags = Tag.all
    end 

    def show
        @tag = Tag.find(params[:id])
    end 
    
    def new
        @tag = Tag.new
    end
     
    def create
        @tag = Tag.new(tag_params)
         if @tag.save
            redirect_to tag_path(@tag)
        else 
            render :new
        end 
    end 
    
    private

    def tag_params
        params.require(:tag).permit(:name)
    end 

end 

app/controllers/users_controller.rb
class UsersController < ApplicationController

    
    def show
        @user = User.find(params[:id])
        @picture = Picture.new
    end 
    
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.valid?
                @user.save
                session[:user_id] = @user.id
                flash[:success] = "Don't Stop Get it Get it!"
                redirect_to user_path(@user)
            else 
                flash[:warning] = "Ya Dun Goofed..."
                render :new
            end 
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyPicsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <nav class="navbar navbar-light bg-light" style="border-bottom: 1px solid black !important;">
    
    <% if logged_in? -%> <%= current_user.username%>
    
    <form class="form-inline">
    <a class="btn btn-outline-primary" href="/users/<%= current_user.id %>"> 
     My Pics
     </a>
     <br>
     <a class="btn btn-outline-primary" href="/pictures"> 
      Browse All Pictures
     </a>
     <br>
     
     <%= link_to "Log out", logout_path, method: "post" %>
     <% else %>
    <a class="navbar-brand" href="/signup">Create User</a>
    <% end %>
    
    </form>
 
</nav>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pictures/index.html.erb
<h1>My Pics</h1>

    <ul>
<% @pictures.each do |picture| %>
        <li>
            <%= picture.title %>
             <%= image_tag(picture.image_url) %>   
                <ul>
            <% picture.tags.each do |tag| %>
                    <li>
                    <%= link_to tag.name, tag_path(tag) %>
                    </li>
                <% end %>
                </ul>
        </li>
<% end %>
    </ul>

app/views/pictures/new.html.erb
<h1> Your Pictures </h1>
 
 <%= @picture.image_url %>

app/views/pictures/show.html.erb
<h1>Picture Title: <%= @picture.title %></h1>

            <%= image_tag(@picture.image_url) %>

            <%= @picture.title %>
            <ul>
            <% @picture.tags.each do |tag| %>
                    <li>
                        
                        <%= link_to tag.name, tag_path(tag) %>
                    </li>
                <% end %>
                </ul>
  

app/views/tags/index.html.erb
<h1>Tag Index</h1>


<% @tags.each do |tag|%>
    <ul>
        <li><%= link_to tag.name, tag_path(tag) %> </li>
    </ul>
    <% end %>

app/views/tags/show.html.erb
<h1>Pictures tagged with <%= @tag.name %></h1>

    <ul>
        <% @tag.pictures.each do |picture|%>
        <li>
        <% picture.title %>
        <%= image_tag(picture.image_url) %>
        </li>
    <% end %>
    </ul>

app/views/users/new.html.erb
<h1>Create a User</h1>

<%= form_for(@user) do |f| %>
<%= f.label :username %>
<%= f.text_field :username %><br>
<%= f.label :email %>
<%= f.text_field :email %><br>
<%= f.label :password %>
<%= f.password_field :password %><br>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %><br>
<%= f.submit %>

<% end %>

app/views/users/show.html.erb
<h1>Welcome to My Pics!</h1>


<h3>All Your Pics</h3>
<%= current_user.pictures.count%>
<h3>Total Pics</h3>
<%= Picture.pictures_total%>

<h1>Pictures</h1>
 
<ul>
<% current_user.pictures.each do |picture| %>
<li>
<%= link_to picture_path(picture) do %>
<%= image_tag(picture.image_url) %>
<%end%>
</li>
<%end%>
</ul>

<h1>Post New Pic</h1>

<%= form_for (@picture) do |f| %>
  <%= f.label :image_url, "Image URL"%>
  <%= f.text_field :image_url %>
  <br>
    
  <%= f.label :title, "Image Title"%>
  <%= f.text_field :title %>

  <br>
 <%= f.hidden_field :user_id, value: @user.id%><br>
 
 <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name %> 
    
    <h2>Create a Tag</h2>

 <%= f.fields_for :tags, @picture.tags.build do |tags_fields| %>
 <%= tags_fields.text_field :name %>
 <% end %>
  
  
  
  <%= f.submit %>
<% end %>
    